### ISSUE TITLE
how can I run this project?

### ISSUE THREAD

**Issue by saaries** [suraj2596/RVO_rospy#1]
![image](https://user-images.githubusercontent.com/28039673/50683386-d8a8a280-104c-11e9-8543-b053ea45edd7.png)

**Comment by saaries** [comment]
sorry to disturb!
First, you write a wonderful article to introduce RVO! Following link
(https://medium.com/@suraj2596/paper-review-reciprocal-velocity-obstacles-for-real-time-multi-agent-navigation-aaf6adbedefd)
In this code, I can't find rvo.msg, and I can't get this file on Github or google.
It would be very kind of you to upload it！
Thank you very much!!

**Comment by suraj2596** [comment]
So, I happen to upload only the core functionality. My bad. That is why you weren't able to fire it up.
Will upload the whole catkin package in some time. 

Regd that message, it is a custom message I made. It is inside the package alongside workspace related files. Reason for using a custom message is : It contains not only the Pose but also the turtle's name. This way, a single ROS topic can be used for sharing information instead of having multiple topics to calculate RVO.

**Comment by suraj2596** [comment]
Updated the repo. It should run fine now. Also added instruction to run this repo. I'm closing this issue for now. If you run into any other problem, reopen this or start a new issue accordingly.

**Comment by wyx1314dd** [comment]
sorry to disturb!
So this msg(rvo.msg) has not appeared in this project, I have the same problem
